import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'
import { useState } from 'react'
import axios from 'axios'
import Link from 'next/link'
import HeaderBar from '@/comps/header'
import Carousel from '@/comps/carousel'

export default function Home() {

    const [data, setData] = useState();
  
    const apiKey = "qO706hvtrjKPLwTwuCZ9XYxHnUPvhtQHSM6Ncmu8";
    const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`
  
    const getTechTransferData = async () => {
      const res = await axios.get(url);
      const info = await res.data;
      console.log(info)
      setData(info)
    }
  
    useEffect(() => {
      getTechTransferData();
    }, [])
  
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderBar />
        <main className={styles.galaxy}>
          {/* <Link href='/polychromatic'>Polychromatic</Link> */}
          <Carousel />
        </main>
      </>
    )
  }
  